apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
  namespace: monitoring
spec:
  secretName: argocd-tls
  duration: 8760h # 365 days
  renewBefore: 360h # 15 days before end
  commonName: grafana.local
  dnsNames:
    - grafana.local
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  usages:
    - server auth
    - client auth
