---
- name: Install Argo CD on Kubernetes master
  hosts: master
  become: yes
  tasks:
    - name: Ensure python3-pip and kubernetes module are installed
      apt:
        name:
          - python3-pip
        state: latest
        update_cache: yes
    
    - name: Install kubernetes Python module
      pip:
        name: kubernetes
        executable: pip3

    - name: Download Helm install script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0755'

    - name: Run Helm install script
      ansible.builtin.shell: bash /tmp/get_helm.sh
      args:
        creates: /usr/local/bin/helm

    - name: Add Argo Helm repository
      kubernetes.core.helm_repository:
        name: argo
        repo_url: https://argoproj.github.io/argo-helm

    - name: Install Argo CD via Helm
      kubernetes.core.helm:
        name: argocd
        chart_ref: argo/argo-cd
        release_namespace: argocd
        create_namespace: true
        update_repo_cache: true
        values:
          redis:
            architecture: standalone
            master:
              persistence:
                enabled: false
          repoServer:
            persistence:
              enabled: false
          dex:
            enabled: false

    - name: Wait until Argo CD is ready
      shell: |
        kubectl wait --namespace argocd \
          --for=condition=ready pod \
          --selector=app.kubernetes.io/name=argocd-repo-server \
          --timeout=300s

    - name: Apply Argo CD default application project (App Project)
      kubernetes.core.k8s:
        state: present
        namespace: argocd
        definition: "{{ lookup('file', '../gitops/0-default-project.yaml') }}"
    
    - name: Apply Cert Manager CRD installation manifest (CRDs)
      kubernetes.core.k8s:
        state: present
        namespace: argocd
        definition: "{{ lookup('file', '../gitops/cert-manager/1-cert-install-crds.yaml') }}"
    
    - name: Apply Cert Manager application manifest (Controller)
      kubernetes.core.k8s:
        state: present
        namespace: argocd
        definition: "{{ lookup('file', '../gitops/cert-manager/2-cert-manager.yaml') }}"
    
    - name: Apply NginX Ingress manifest
      kubernetes.core.k8s:
        state: present
        namespace: argocd
        definition: "{{ lookup('file', '../gitops/apps/nginx-ingress/nginx-ingress.yaml') }}"
        
    - name: Apply Metal Load Balancer manifest
      kubernetes.core.k8s:
        state: present
        namespace: argocd
        definition: "{{ lookup('file', '../gitops/apps/metal-load-balancer/metal-load-balancer.yaml') }}"
    
    - name: Apply Cert Manager resources manifest (Resources)
      kubernetes.core.k8s:
        state: present
        namespace: argocd
        definition: "{{ lookup('file', '../gitops/cert-manager/3-cert-manager-resources.yaml') }}"
    
    - name: Apply Argo CD root application manifest (App of Apps)
      kubernetes.core.k8s:
        state: present
        namespace: argocd
        definition: "{{ lookup('file', '../gitops/4-root-application.yaml') }}"
