apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  description: Default Argo CD project
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
