apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/requeue-after-seconds: "60"
spec:
  project: default
  source:
    repoURL: 'https://github.com/sittollsCM/devops-iitu-infra'
    targetRevision: HEAD
    path: gitops/apps
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
