controller:
  replicaCount: 1
  service:
    type: LoadBalancer
    ports:
      http: 80
      https: 443
  ingressClassResource:
    name: nginx
    default: true
  admissionWebhooks:
    enabled: false