alertmanager:
  enabled: true

server:
  persistentVolume:
    enabled: true
    size: 8Gi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi

service:
  type: ClusterIP
  port: 9090
