loki:
  persistence:
    enabled: true
    size: 10Gi

  commonConfig:
    replication_factor: 1

  storage:
    type: filesystem

read:
  replicas: 1

write:
  replicas: 1

ingester:
  replicas: 1
