loki:
  persistence:
    enabled: true
    size: 10Gi

  commonConfig:
    replication_factor: 1

  storage:
    type: filesystem
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
    filesystem:
      directory: /var/loki/chunks

  schemaConfig:
    configs:
      - from: 2023-01-01
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h

read:
  replicas: 1

write:
  replicas: 1

ingester:
  replicas: 1
